### ISSUE TITLE
Unhandled Exceptions

### ISSUE THREAD

**Issue by salstein** [thruthesky/fireflutter#28]
I already created a Firebase project which was initially working very fine. But after i added fireFlutter dependency I started get Unhandled Exceptions anytime i try accessing the device Camera or Gallery.

`E/ample.lcnetwor( 7069): Timed out waiting for threads to suspend, waited for 15.288s
E/ample.lcnetwor( 7069): Thread not suspended: Thread[4,tid=7077,Runnable,Thread*=0xdbbc2a10,peer=0x13241900,"Signal Catcher"]
W/libbacktrace( 7069): bool ThreadEntry::Wait(int): pthread_cond_timedwait for value 3 failed: Connection timed out
W/libbacktrace( 7069): bool BacktraceCurrent::UnwindThread(size_t): Timed out waiting for signal handler to indicate it finished.
E/ample.lcnetwor( 7069): Timed out waiting for threads to suspend, waited for 25.289s
E/ample.lcnetwor( 7069): Thread not suspended: Thread[4,tid=7077,Runnable,Thread*=0xdbbc2a10,peer=0x13241900,"Signal Catcher"]
W/libbacktrace( 7069): bool ThreadEntry::Wait(int): pthread_cond_timedwait for value 2 failed: Connection timed out
E/libbacktrace( 7069): void SignalHandler(int, siginfo_t *, void *): Timed out waiting for unwind thread to indicate it completed.
E/ample.lcnetwor( 7069): Timed out waiting for threads to suspend, waited for 35.289s
E/ample.lcnetwor( 7069): Thread not suspended: Thread[4,tid=7077,Runnable,Thread*=0xdbbc2a10,peer=0x13241900,"Signal Catcher"]
E/ample.lcnetwor( 7069): Timed out waiting for threads to suspend, waited for 45.291s
E/ample.lcnetwor( 7069): Thread not suspended: Thread[4,tid=7077,Runnable,Thread*=0xdbbc2a10,peer=0x13241900,"Signal Catcher"]
W/libbacktrace( 7069): bool ThreadEntry::Wait(int): pthread_cond_timedwait for value 3 failed: Connection timed out
W/libbacktrace( 7069): bool BacktraceCurrent::UnwindThread(size_t): Timed out waiting for signal handler to indicate it finished.
W/ample.lcnetwor( 7069): Suspending all threads took: 54.691s
I/ample.lcnetwor( 7069): Wrote stack traces to tombstoned
W/ample.lcnetwor( 7069): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/ample.lcnetwor( 7069): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/ample.lcnetwor( 7069): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
W/FirebaseInstanceId( 7069): Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
D/HostConnection( 7069): HostConnection::get() New Host Connection established 0xe9862280, tid 7112
D/HostConnection( 7069): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2
W/OpenGLRenderer( 7069): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
I/Gralloc4( 7069): mapper 4.x is not supported
W/FA      ( 7069): Tasks have been queued for a long time
D/HostConnection( 7069): createUnique: call
D/HostConnection( 7069): HostConnection::get() New Host Connection established 0xe98649e0, tid 7121
D/goldfish-address-space( 7069): allocate: Ask for block of size 0x100
D/goldfish-address-space( 7069): allocate: ioctl allocate returned offset 0x3fe1bc000 size 0x2000
D/HostConnection( 7069): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2
D/HostConnection( 7069): HostConnection::get() New Host Connection established 0xe9863f60, tid 7121
D/HostConnection( 7069): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2
D/EGL_emulation( 7069): eglMakeCurrent: 0xe98436c0: ver 2 0 (tinfo 0xe9bbbcb0) (first time)
D/EGL_emulation( 7069): eglCreateContext: 0xe9864660: maj 2 min 0 rcv 2
D/EGL_emulation( 7069): eglMakeCurrent: 0xe9864660: ver 2 0 (tinfo 0xe9bbb310) (first time)
I/OpenGLRenderer( 7069): Davey! duration=7619ms; Flags=1, IntendedVsync=3481365553498, Vsync=3481398886830, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=3481409267000, AnimationStart=3481409320600, PerformTraversalsStart=3481409384100, DrawStart=3488900796600, SyncQueued=3488912790000, SyncStart=3488945708800, IssueDrawCommandsStart=3488946392100, SwapBuffers=3488979987300, FrameCompleted=3489018387300, DequeueBufferDuration=22927600, QueueBufferDuration=5829100, GpuCompleted=0,
I/Choreographer( 7069): Skipped 460 frames!  The application may be doing too much work on its main thread.
W/ample.lcnetwor( 7069): JNI critical lock held for 36.237ms on Thread[25,tid=7243,Runnable,Thread*=0xdbbd4210,peer=0x12e80ae8,"Measurement Worker"]
W/DynamiteModule( 7069): Local module descriptor class for providerinstaller not found.
I/ample.lcnetwor( 7069): Background young concurrent copying GC freed 3141(426KB) AllocSpace objects, 8(276KB) LOS objects, 2% free, 3282KB/3364KB, paused 1.846ms total 205.913ms
I/DynamiteModule( 7069): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 7069): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/ample.lcnetwor( 7069): The ClassLoaderContext is a special shared library.
I/ample.lcnetwor( 7069): Background concurrent copying GC freed 39990(2202KB) AllocSpace objects, 11(788KB) LOS objects, 49% free, 3539KB/7079KB, paused 2.717ms total 2.006s
I/ample.lcnetwor( 7069): The ClassLoaderContext is a special shared library.
I/ample.lcnetwor( 7069): The ClassLoaderContext is a special shared library.
D/nativeloader( 7069): classloader namespace configured for unbundled product apk. library_path=/product/priv-app/PrebuiltGmsCore/lib/x86:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/product/lib:/system/product/lib
V/NativeCrypto( 7069): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/ample.lcnetwor( 7069): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/ProviderInstaller( 7069): Installed default security provider GmsCore_OpenSSL
E/flutter ( 7069): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 7069): 
E/flutter ( 7069): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 7069): 
I/ample.lcnetwor( 7069): Thread[4,tid=7077,WaitingInMainSignalCatcherLoop,Thread*=0xdbbc2a10,peer=0x13241900,"Signal Catcher"]: reacting to signal 3
I/ample.lcnetwor( 7069): 
W/ample.lcnetwor( 7069): Suspending all threads took: 99.459ms
W/ManagedChannelImpl( 7069): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl( 7069): [{0}] Failed to resolve name. status={1}
I/libc    ( 7069): Requested dump for tid 7069 (ample.lcnetwork)
I/ample.lcnetwor( 7069): Wrote stack traces to tombstoned
W/ManagedChannelImpl( 7069): [{0}] Failed to resolve name. status={1}
E/FirebaseInstanceId( 7069): Failed to get FIS auth token
E/FirebaseInstanceId( 7069): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 7069):    at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/FirebaseInstanceId( 7069):    at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-iid@@21.0.0:55)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.0.0:37)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.0.0:13)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$1$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.0.0:158)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:8)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.0.0:14)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(com.google.firebase:firebase-iid@@21.0.0:157)
E/FirebaseInstanceId( 7069):    at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
E/FirebaseInstanceId( 7069):    at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
E/FirebaseInstanceId( 7069):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 7069):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 7069):    at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.1.0:6)
E/FirebaseInstanceId( 7069):    at java.lang.Thread.run(Thread.java:923)
E/FirebaseInstanceId( 7069): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 7069):    at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:200)
E/FirebaseInstanceId( 7069):    at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:490)
E/FirebaseInstanceId( 7069):    at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:361)
E/FirebaseInstanceId( 7069):    at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:351)
E/FirebaseInstanceId( 7069):    at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(Unknown Source:4)
E/FirebaseInstanceId( 7069):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 7069):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 7069):    ... 1 more
W/FirebaseInstanceId( 7069): Token retrieval failed: SERVICE_NOT_AVAILABLE. Will retry token retrieval
I/Choreographer( 7069): Skipped 67 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer( 7069): Davey! duration=1174ms; Flags=0, IntendedVsync=3560148886021, Vsync=3561265552643, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=3561267773000, AnimationStart=3561267867500, PerformTraversalsStart=3561268308000, DrawStart=3561308240500, SyncQueued=3561311160500, SyncStart=3561313017300, IssueDrawCommandsStart=3561313144700, SwapBuffers=3561317392400, FrameCompleted=3561324952300, DequeueBufferDuration=1869500, QueueBufferDuration=4723700, GpuCompleted=0,
E/flutter ( 7069): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
E/flutter ( 7069): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 7069): <asynchronous suspension>
E/flutter ( 7069): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 7069): #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:66:30)
E/flutter ( 7069): #3      PermissionListActions.request (package:permission_handler/permission_handler.dart:109:16)
E/flutter ( 7069): #4      PermissionActions.request (package:permission_handler/permission_handler.dart:49:26)
E/flutter ( 7069): #5      PhotoUpload.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:lcnetwork/photo_upload.dart:25:45)
E/flutter ( 7069): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 7069): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 7069): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 7069): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 7069): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 7069): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 7069): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 7069): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 7069): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 7069): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 7069): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 7069): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 7069): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 7069): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 7069): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 7069): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 7069): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 7069): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 7069): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 7069): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7069): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7069): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 7069): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 7069):
W/ManagedChannelImpl( 7069): [{0}] Failed to resolve name. status={1}
W/ManagedChanne`

**Comment by salstein** [comment]
I already tried every suggested solutions on GitHub and StackOverflow
