### ISSUE TITLE
User Doc is having a problem upon startup

### ISSUE THREAD

**Issue by withcenter-dev2** [thruthesky/fireflutter#64]
<img width="1119" alt="image" src="https://github.com/thruthesky/fireflutter/assets/119567064/490d1e97-fd17-4120-8e75-7c75100e3dcd">

This issue will not always show. 

<img width="460" alt="image" src="https://github.com/thruthesky/fireflutter/assets/119567064/0b98a4f1-8a82-4269-a07c-ee5f586dace7">

_Possibly because "my" is not loaded yet when it was being used upon startup._

**Comment by withcenter-dev2** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building FutureBuilder<User?>(dirty, state: _FutureBuilderState<User?>#b0f13):
Null check operator used on a null value

The relevant error-causing widget was
FutureBuilder<User?>
user_doc.dart:75
When the exception was thrown, this was the stack
#0      _FeedEditScreenState.build.<anonymous closure>
feed.edit.screen.dart:219
#1      UserDoc.buildStreamWidget
user_doc.dart:140
#2      _FutureBuilderState.build
async.dart:612
#3      StatefulElement.build
framework.dart:5409
#4      ComponentElement.performRebuild
framework.dart:5297
#5      StatefulElement.performRebuild
framework.dart:5462
#6      Element.rebuild
framework.dart:5016
#7      BuildOwner.buildScope
framework.dart:2779
#8      WidgetsBinding.drawFrame
binding.dart:916
#9      RendererBinding._handlePersistentFrameCallback
binding.dart:360
#10     SchedulerBinding._invokeFrameCallback
binding.dart:1297
#11     SchedulerBinding.handleDrawFrame
binding.dart:1227
#12     SchedulerBinding._handleDrawFrame
binding.dart:1085
#13     _invoke (dart:ui/hooks.dart:170:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#15     _drawFrame (dart:ui/hooks.dart:140:31)
════════════════════════════════════════════════════════════════════════════════
